[phases.setup]
nixPkgs = ["nodejs_22", "npm-10_x"]

[phases.build]
cmds = [
    "npm run build",
    "cp -r public .next/standalone/public",
    "cp -r .next/static .next/standalone/.next/static",
]

[start]
cmd = "node .next/standalone/server.js"
